# Generated by Django 5.1.4 on 2024-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0007_adminaddflight'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaddflight',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
