# Generated by Django 5.1.4 on 2024-12-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0009_remove_adminaddflight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaddflight',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
