# Generated by Django 5.1.4 on 2025-01-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=13),
        ),
    ]
